### PR TITLE
[add] messaging module to encapsulate flash messages

### PR DESCRIPTION
**Pull request by connorlay**
Flash messages are stored as constants in the Messaging::ControllerName namespace and accessed by calling them as class methods.

### CODE REVIEW

**Comment by efatsi** [comment]
Nice solution. Your method call -> `method_missing` -> constant lookup has a touch of code smell but this is good work.

**Comment by h0tl33t** [comment]
Rails provides YAML-based dictionary functionality for the string representation of things through [`I18n`](http://guides.rubyonrails.org/i18n.html).  You've basically rolled your own, which is cool!

Two things:
1) In your tests, since you're replacing all the explicit message assertions with the abstractions -- you're asserting that some text is showing up, but you lose the guarantee of what that text actually is.  If something was misspelled or someone down the road accidentally mixed up the messages.. you'd never know based on your tests.

In this case, it's probably worth adding some unit tests around your `Messages` module to ensure the strings it outputs are correct.

2) I, personally, think it'd be really cool to have a flash-specific DSL for your `Messages` like:
```ruby
redirect_to root_url, flash: Messaging::Sessions::create_success(@user).for_flash
```

If you're up for it, take a crack at it yourself or hit me up if you'd like to pair on it.

Overall, nice refactor!  :poultry_leg:

**Comment by connorlay** [comment]
@efatsi Since Rails already uses the ```method_missing``` override approach to do its magic, I figured this was an appropriate solution. What would be some good alternatives to avoid traversing the method lookup tree for constants?
@h0tl33t A flash-specific DSL sounds cool. We should pair at some point and work on it!

**Comment by efatsi** [comment]
Yeah, it's a smell but nothing so bad that I'd strongly recommend you change it. Alternative options would be to just go all methods instead of using constants, or refer to the constants themselves.

**Pull request closed without merging**
